language: scala
scala:
- 2.12.8
- 2.11.12
- 2.13.0
jdk:
- oraclejdk8
script: sbt -batch "++${TRAVIS_SCALA_VERSION}!" scalafmtCheck test:scalafmtCheck scalafmtSbtCheck test:compile testJVM/test testJS/test
sudo: false
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
matrix:
  include:
  - scala: 2.11.12
    dist: trusty
    sudo: required
    env: NATIVE=1
    before_install:
    - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
    script:
    - sbt "++${TRAVIS_SCALA_VERSION}!" testNative/test
